const RHYTHM_RESEARCH_SEED_VERSION = "2026-05-10-a";

const rhythmResearchSeed = [
  {
    id: "tonejs-core",
    name: "Tone.js",
    category: "engine",
    role: "Transport, sampler, synth, timing, FX bus",
    fit: "Best first drum engine for JamPal Drummer because it already solves transport-grade scheduling and browser-friendly instrument routing.",
    rhythmValue: "Lets us schedule kick, snare, hats, fills, swing and humanization with musical time instead of fragile UI timers.",
    status: "recommended-now",
    packageName: "tone",
    currentVersionNote: "npm latest 15.1.22, with newer 15.3.x builds published in May 2026",
    sourceUrls: [
      "https://tonejs.github.io/",
      "https://tonejs.github.io/docs/14.5.3/Transport",
      "https://tonejs.github.io/docs/15.1.22/classes/Sampler.html",
      "https://www.npmjs.com/package/tone?activeTab=versions",
    ],
  },
  {
    id: "essentia-js",
    name: "Essentia.js",
    category: "analysis",
    role: "Beat, onset, energy and feature extraction",
    fit: "Strong candidate for the analysis layer because it exposes a broad Music Information Retrieval toolkit in WebAssembly.",
    rhythmValue: "Good for onset tracking, energy descriptors, spectral features and later tempo confidence features feeding the groove brain.",
    status: "recommended-now",
    packageName: "essentia.js",
    currentVersionNote: "Official docs point to current releases on GitHub and npm; npm package page highlights real-time and offline analysis support",
    sourceUrls: [
      "https://mtg.github.io/essentia.js/docs/api/",
      "https://www.npmjs.com/package/essentia.js/v/0.1.3",
    ],
  },
  {
    id: "web-audio-beat-detector",
    name: "web-audio-beat-detector",
    category: "analysis",
    role: "Fast BPM and first-beat guess from AudioBuffer",
    fit: "Useful lightweight helper for player-loaded files before we deploy heavier live tracking.",
    rhythmValue: "Can quickly estimate BPM and beat offset for preloaded tracks, especially electronic or steady material.",
    status: "recommended-now",
    packageName: "web-audio-beat-detector",
    currentVersionNote: "npm page shows 8.2.19 published a month ago",
    sourceUrls: [
      "https://www.npmjs.com/package/web-audio-beat-detector?activeTab=code",
    ],
  },
  {
    id: "realtime-bpm-analyzer",
    name: "Realtime BPM Analyzer",
    category: "analysis",
    role: "Live BPM estimation for audio or video nodes and streams",
    fit: "Worth comparing against Essentia.js for live following on the player path or microphone path.",
    rhythmValue: "Can estimate BPM while media is already running, which is handy when JamPal must join mid-performance.",
    status: "watchlist",
    packageName: "realtime-bpm-analyzer",
    currentVersionNote: "npm page lists 4.0.2 as latest",
    sourceUrls: [
      "https://www.npmjs.com/package/realtime-bpm-analyzer?activeTab=versions",
    ],
  },
  {
    id: "magenta-music",
    name: "Magenta.js Music",
    category: "ai",
    role: "Model-driven drum and pattern variation generation",
    fit: "Better as a later creative layer than as the timing authority.",
    rhythmValue: "Useful for fill suggestions, groove mutations and alternate drum ideas once the rule-based engine is already stable.",
    status: "later-phase",
    packageName: "@magenta/music",
    currentVersionNote: "npm latest is 1.23.1; package has not seen a fresh release in several years, so treat as optional and contained",
    sourceUrls: [
      "https://github.com/magenta/magenta-js",
      "https://www.npmjs.com/package/%40magenta/music",
    ],
  },
  {
    id: "tonejs-audio",
    name: "Tonejs/audio",
    category: "sample-library",
    role: "Starter audio repository with drum samples, loops and impulse responses",
    fit: "Very practical for prototyping because it matches Tone.js usage patterns directly.",
    rhythmValue: "Gives us quick-access drum samples and loops for early JamPal drummer sketches before curating our own kit.",
    status: "recommended-now",
    packageName: null,
    currentVersionNote: "GitHub repo used for Tone.js example audio",
    sourceUrls: [
      "https://github.com/Tonejs/audio",
    ],
  },
  {
    id: "freesound-api",
    name: "Freesound API",
    category: "sample-api",
    role: "Searchable sound and pack library with analysis descriptors",
    fit: "Strong option when we want tagged percussion, disco one-shots, loops or texture FX with searchable metadata.",
    rhythmValue: "The API exposes descriptors such as bpm, bpm_confidence, onset_count and onset_times that are very relevant to rhythmic asset discovery.",
    status: "recommended-now",
    packageName: null,
    currentVersionNote: "APIv2 docs active; original-sound download needs OAuth2 while preview access is easier",
    sourceUrls: [
      "https://freesound.org/docs/api/",
      "https://freesound.org/docs/api/analysis_docs.html",
      "https://freesound.org/help/about/",
    ],
  },
  {
    id: "salamander-drumkit",
    name: "Salamander Drumkit",
    category: "sample-library",
    role: "Open acoustic drum kit in SFZ format",
    fit: "Good candidate when we want a more organic backing drummer than pure drum-machine hits.",
    rhythmValue: "Multi-sample acoustic kit with many hat variations can help the drummer feel less robotic once a sampler layer is ready.",
    status: "watchlist",
    packageName: null,
    currentVersionNote: "GitHub mirror documents CC BY-SA licensing and broad kit coverage",
    sourceUrls: [
      "https://github.com/endolith/Salamander-Drumkit",
    ],
  },
  {
    id: "stargate-sample-pack",
    name: "Stargate Sample Pack",
    category: "sample-library",
    role: "Open/public-domain leaning sample source for redistribution-friendly prototypes",
    fit: "Interesting if we want small redistributable starter kits inside JamPal experiments.",
    rhythmValue: "Could supply permissive percussion and FX material for bundled drummer presets.",
    status: "watchlist",
    packageName: null,
    currentVersionNote: "GitHub search result describes it as open source and public domain oriented",
    sourceUrls: [
      "https://github.com/stargatedaw/stargate-sample-pack",
    ],
  },
];

export { RHYTHM_RESEARCH_SEED_VERSION, rhythmResearchSeed };
