export const defaultSkinId = "midnight-signal";

export const skinCatalog = [
  {
    id: "midnight-signal",
    name: "Midnight Signal",
    description: "Dark studio palette with crisp electric blue controls.",
    swatches: ["#0f1115", "#1f2731", "#6cb8ff", "#c1ff72"],
    variables: {
      "--bg": "#0f1115",
      "--bg-accent": "radial-gradient(circle at top right, rgba(108, 184, 255, 0.18), transparent 34%), radial-gradient(circle at bottom left, rgba(193, 255, 114, 0.12), transparent 28%)",
      "--panel": "#171d25",
      "--panel-2": "#10151b",
      "--panel-3": "#212a35",
      "--field": "#222c38",
      "--field-border": "#3b4a5d",
      "--text": "#f3f6fb",
      "--muted": "#a9b7c8",
      "--accent": "#6cb8ff",
      "--accent-soft": "#17324f",
      "--accent-strong": "#8fd0ff",
      "--tab": "#1e2530",
      "--tab-active": "#243244",
      "--tab-border": "#3b4a5d",
      "--button-hover": "#2b3643",
      "--meter-a": "#55c2ff",
      "--meter-b": "#9ce663",
      "--meter-c": "#facc15",
      "--canvas-frame": "#0b0d11",
      "--shadow": "0 22px 80px rgba(0, 0, 0, 0.42)",
      "--font-ui": "\"Segoe UI\", Tahoma, Geneva, Verdana, sans-serif",
      "--font-display": "\"Trebuchet MS\", \"Segoe UI\", sans-serif",
    },
  },
  {
    id: "amber-console",
    name: "Amber Console",
    description: "Broadcast desk look with warm amber highlights and deep graphite surfaces.",
    swatches: ["#15110d", "#2a2118", "#ffb14a", "#ffe0a8"],
    variables: {
      "--bg": "#15110d",
      "--bg-accent": "radial-gradient(circle at top left, rgba(255, 177, 74, 0.18), transparent 32%), radial-gradient(circle at bottom right, rgba(255, 224, 168, 0.10), transparent 30%)",
      "--panel": "#201913",
      "--panel-2": "#16110d",
      "--panel-3": "#32261c",
      "--field": "#2a2118",
      "--field-border": "#5d4835",
      "--text": "#fff5e7",
      "--muted": "#d9c2a7",
      "--accent": "#ffb14a",
      "--accent-soft": "#4b2f14",
      "--accent-strong": "#ffd289",
      "--tab": "#261d16",
      "--tab-active": "#3a2a1c",
      "--tab-border": "#5d4835",
      "--button-hover": "#3a2d22",
      "--meter-a": "#ff9f43",
      "--meter-b": "#ffd166",
      "--meter-c": "#fff08a",
      "--canvas-frame": "#0d0907",
      "--shadow": "0 22px 80px rgba(0, 0, 0, 0.5)",
      "--font-ui": "\"Segoe UI\", Tahoma, Geneva, Verdana, sans-serif",
      "--font-display": "\"Georgia\", \"Segoe UI\", serif",
    },
  },
  {
    id: "sea-glass",
    name: "Sea Glass",
    description: "Soft teal surfaces with a brighter daylight control treatment.",
    swatches: ["#dff4f1", "#ffffff", "#1f8f83", "#0f5f6f"],
    variables: {
      "--bg": "#dff4f1",
      "--bg-accent": "radial-gradient(circle at top right, rgba(31, 143, 131, 0.20), transparent 30%), radial-gradient(circle at bottom left, rgba(15, 95, 111, 0.16), transparent 26%)",
      "--panel": "#f8fcfb",
      "--panel-2": "#edf7f5",
      "--panel-3": "#d8ece8",
      "--field": "#ffffff",
      "--field-border": "#9ac6c0",
      "--text": "#15333d",
      "--muted": "#54737b",
      "--accent": "#1f8f83",
      "--accent-soft": "#d7f0ec",
      "--accent-strong": "#0f5f6f",
      "--tab": "#e6f4f1",
      "--tab-active": "#ffffff",
      "--tab-border": "#9ac6c0",
      "--button-hover": "#e4f3ef",
      "--meter-a": "#1f8f83",
      "--meter-b": "#42b883",
      "--meter-c": "#b4d455",
      "--canvas-frame": "#cfe9e4",
      "--shadow": "0 22px 70px rgba(23, 74, 77, 0.18)",
      "--font-ui": "\"Segoe UI\", Tahoma, Geneva, Verdana, sans-serif",
      "--font-display": "\"Lucida Sans\", \"Segoe UI\", sans-serif",
    },
  },
  {
    id: "signal-flare",
    name: "Signal Flare",
    description: "Punchier coral and citrus accents for a more performative control room.",
    swatches: ["#1d1011", "#2d1a1c", "#ff6b57", "#f4d35e"],
    variables: {
      "--bg": "#1d1011",
      "--bg-accent": "radial-gradient(circle at top center, rgba(255, 107, 87, 0.22), transparent 30%), radial-gradient(circle at bottom left, rgba(244, 211, 94, 0.16), transparent 28%)",
      "--panel": "#271618",
      "--panel-2": "#180d0e",
      "--panel-3": "#332022",
      "--field": "#2d1a1c",
      "--field-border": "#6f4448",
      "--text": "#fff1ee",
      "--muted": "#d8b6b2",
      "--accent": "#ff6b57",
      "--accent-soft": "#4d221f",
      "--accent-strong": "#ff9a7e",
      "--tab": "#2a1719",
      "--tab-active": "#3a2123",
      "--tab-border": "#6f4448",
      "--button-hover": "#402527",
      "--meter-a": "#ff6b57",
      "--meter-b": "#ff8c42",
      "--meter-c": "#f4d35e",
      "--canvas-frame": "#110809",
      "--shadow": "0 22px 80px rgba(0, 0, 0, 0.46)",
      "--font-ui": "\"Segoe UI\", Tahoma, Geneva, Verdana, sans-serif",
      "--font-display": "\"Arial Black\", \"Segoe UI\", sans-serif",
    },
  },
];

export function getSkinById(id) {
  return skinCatalog.find((skin) => skin.id === id) || skinCatalog[0];
}

export function applySkin(root, skin) {
  root.dataset.skin = skin.id;
  Object.entries(skin.variables).forEach(([key, value]) => {
    root.style.setProperty(key, value);
  });
}
